// <auto-generated />
using System;
using Ex2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ex2.Migrations
{
    [DbContext(typeof(TaskAssignmentContext))]
    partial class TaskAssignmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ex2.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DOB")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<float?>("PayRate")
                        .HasColumnType("real");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "Hanoi",
                            DOB = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@yahoo.com",
                            FullName = "A A",
                            PayRate = 7f,
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "Hanoi",
                            DOB = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "b@yahoo.com",
                            FullName = "B B",
                            PayRate = 12f,
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "Hanoi",
                            DOB = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "c@yahoo.com",
                            FullName = "C C",
                            PayRate = 10.5f,
                            PhoneNumber = "0912345678"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "Hanoi",
                            DOB = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "d@yahoo.com",
                            FullName = "D D",
                            PayRate = 5.4f,
                            PhoneNumber = "0912345678"
                        });
                });

            modelBuilder.Entity("Ex2.Entities.EmployeeTemp", b =>
                {
                    b.Property<int>("EmployeeTempID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("PayRate")
                        .HasColumnType("real");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTempID");

                    b.ToTable("EmployeeTemp");
                });

            modelBuilder.Entity("Ex2.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ProjectID");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            Description = "1",
                            Note = "1",
                            ProjectName = "Project1"
                        },
                        new
                        {
                            ProjectID = 2,
                            Description = "2",
                            Note = "2",
                            ProjectName = "Project2"
                        },
                        new
                        {
                            ProjectID = 3,
                            Description = "3",
                            Note = "3",
                            ProjectName = "Project3"
                        });
                });

            modelBuilder.Entity("Ex2.Entities.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("TaskID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            EmployeeID = 1,
                            ProjectID = 1,
                            WorkingHours = 50
                        },
                        new
                        {
                            TaskID = 2,
                            EmployeeID = 2,
                            ProjectID = 2,
                            WorkingHours = 33
                        },
                        new
                        {
                            TaskID = 3,
                            EmployeeID = 3,
                            ProjectID = 3,
                            WorkingHours = 77
                        });
                });

            modelBuilder.Entity("Ex2.Entities.TaskTemp", b =>
                {
                    b.Property<int>("TaskTempID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("TaskID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("TaskTempID");

                    b.ToTable("TaskTemp");
                });

            modelBuilder.Entity("Ex2.Entities.Task", b =>
                {
                    b.HasOne("Ex2.Entities.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("Ex2.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID");
                });
#pragma warning restore 612, 618
        }
    }
}
